#!/usr/bin/env python3
"""Build the tier-filtered skill catalog for foundation-prioritized-action-plan.

Reads every skills/*/SKILL.md frontmatter and emits a markdown catalog of the
skills that the prioritized-action-plan skill is allowed to recommend in its
Section 7. Tier 1 (phase skills + core foundation) and Tier 2 (conditional) are
emitted; Tier 3 (library machinery) and the skill itself are omitted.

Read, filter, emit. No transformation. Skills whose frontmatter cannot be parsed
are skipped with a warning rather than crashing the build.

Usage:
    python scripts/build-skill-catalog.py
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
OUT = SKILLS_DIR / "foundation-prioritized-action-plan" / "references" / "skill-catalog.md"

PHASES = {"discover", "define", "develop", "deliver", "measure", "iterate"}
TIER1_FOUNDATION = {
    "foundation-persona",
    "foundation-lean-canvas",
    "foundation-okr-writer",
    "foundation-stakeholder-update",
}
TIER3 = {
    "utility-pm-skill-builder",
    "utility-pm-skill-auditor",
    "utility-pm-skill-validate",
    "utility-pm-skill-iterate",
    "utility-pm-release-conductor",
    "utility-pm-changelog-curator",
    "utility-update-pm-skills",
}
SELF = "foundation-prioritized-action-plan"


def parse_frontmatter(text: str) -> dict | None:
    """Return name, description, and category (phase else classification) or None."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fm = text[3:end]
    name = description = phase = classification = None
    in_metadata = False
    for line in fm.splitlines():
        if line.startswith("name:"):
            name = line.split(":", 1)[1].strip()
        elif line.startswith("description:"):
            description = line.split(":", 1)[1].strip()
        elif line.startswith("metadata:"):
            in_metadata = True
        elif in_metadata and line.startswith("  phase:"):
            phase = line.split(":", 1)[1].strip()
        elif in_metadata and line.startswith("  classification:"):
            classification = line.split(":", 1)[1].strip()
    if not name:
        return None
    category = phase or classification or "unknown"
    return {"name": name, "description": description or "", "category": category}


def excerpt(description: str, limit: int = 140) -> str:
    """First sentence or clause of the description, trimmed to limit chars."""
    text = description.strip()
    for stop in (". ", ": "):
        idx = text.find(stop)
        if 0 < idx < limit:
            return text[:idx]
    return text[:limit].rstrip()


def tier_of(name: str, category: str) -> int:
    if name == SELF or name in TIER3:
        return 3
    if category in PHASES or name in TIER1_FOUNDATION:
        return 1
    return 2


def main() -> int:
    tier1: list[dict] = []
    tier2: list[dict] = []
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        meta = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        if meta is None:
            print(f"warning: could not parse frontmatter, skipping {skill_md}", file=sys.stderr)
            continue
        tier = tier_of(meta["name"], meta["category"])
        if tier == 3:
            continue
        (tier1 if tier == 1 else tier2).append(meta)

    lines: list[str] = []
    lines.append("# Skill catalog (tier-filtered, generated)")
    lines.append("")
    lines.append("Generated by `scripts/build-skill-catalog.py`. Do not edit by hand.")
    lines.append("Tier 3 (library machinery) and this skill itself are intentionally omitted.")
    lines.append("Section 7 may name any skill below; Tier 2 only when its context matches.")
    lines.append("")
    lines.append(f"Tier 1 (always recommendable): {len(tier1)} | Tier 2 (conditional): {len(tier2)}")
    lines.append("")
    for title, group in (("Tier 1: always recommendable", tier1), ("Tier 2: conditional", tier2)):
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Skill | Category | What it does |")
        lines.append("|---|---|---|")
        for meta in sorted(group, key=lambda m: (m["category"], m["name"])):
            lines.append(f"| `{meta['name']}` | {meta['category']} | {excerpt(meta['description'])} |")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(tier1)} Tier 1, {len(tier2)} Tier 2)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
