// scripts/gen-resource-index.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseManifest, toRoute, scenarioLabel, cell, repoLink, buildModel, collectSources, ROOT } from './gen-resource-index.mjs';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

test('parseManifest strips index.html and keeps trailing slash', () => {
  const routes = parseManifest('/index.html\n/guides/prompt-gallery/index.html\n/404.html\n\n');
  assert.ok(routes.has('/'));
  assert.ok(routes.has('/guides/prompt-gallery/'));
  assert.ok(routes.has('/404.html'));
  assert.equal(routes.has('/guides/prompt-gallery/index.html'), false);
});

test('toRoute maps doc-relative paths to site routes', () => {
  assert.equal(toRoute('guides/prompt-gallery.md'), '/guides/prompt-gallery/');
  assert.equal(toRoute('guides/index.md'), '/guides/');
  assert.equal(toRoute('index.mdx'), '/');
  assert.equal(toRoute('reference/skill-families/index.md'), '/reference/skill-families/');
});

test('scenarioLabel strips the sample_<skill>_ prefix and humanizes', () => {
  assert.equal(
    scenarioLabel('sample_deliver-prd_storevine_campaigns', 'deliver-prd'),
    'storevine / campaigns',
  );
});

test('cell escapes pipes and collapses newlines', () => {
  assert.equal(cell('a | b\nc'), 'a \\| b c');
});

test('cell escapes backslashes before pipes (complete escaping)', () => {
  assert.equal(cell('a\\b|c'), 'a\\\\b\\|c');
});

test('repoLink prefixes ../ and normalizes separators', () => {
  assert.equal(repoLink('skills/deliver-prd/SKILL.md'), '../skills/deliver-prd/SKILL.md');
});

test('scenarioLabel treats a regex-metachar skill name literally', () => {
  assert.equal(scenarioLabel('sample_a.b_x', 'a.b'), 'x');
  assert.equal(scenarioLabel('sample_axb_x', 'a.b'), 'sample / axb / x');
});

test('toRoute is case-insensitive on the extension', () => {
  assert.equal(toRoute('reference/THING.MD'), '/reference/THING/');
});

test('repoLink normalizes Windows backslashes', () => {
  assert.equal(repoLink('skills\\deliver-prd\\SKILL.md'), '../skills/deliver-prd/SKILL.md');
});

test('buildModel: every live route exists in the manifest', () => {
  const model = buildModel(ROOT);
  const allRows = [
    ...model.docs.flatMap((s) => s.rows),
    ...model.skills.flatMap((g) => g.rows),
    ...model.workflows,
    ...model.samples.flatMap((s) => s.rows),
    ...model.showcase,
  ];
  assert.ok(allRows.length > 200, `expected 200+ rows, got ${allRows.length}`);
  for (const r of allRows) assert.ok(model.routes.has(r.route), `route missing from manifest: ${r.route}`);
});

test('buildModel: every repo source is a tracked file that exists on disk', () => {
  const model = buildModel(ROOT);
  for (const src of collectSources(model)) {
    assert.ok(existsSync(join(ROOT, src)), `repo source missing on disk: ${src}`);
    assert.ok(!src.startsWith('site/src/content/docs/samples/'), `must not link gitignored mirror: ${src}`);
    assert.ok(!src.startsWith('site/src/content/docs/skills/'), `must not link gitignored mirror: ${src}`);
  }
});

test('buildModel: skills are grouped and deliver-prd resolves to its nested route', () => {
  const model = buildModel(ROOT);
  const deliver = model.skills.find((g) => g.group === 'deliver');
  assert.ok(deliver, 'deliver group present');
  const prd = deliver.rows.find((r) => r.name === 'deliver-prd');
  assert.ok(prd, 'deliver-prd present');
  assert.equal(prd.route, '/skills/deliver/deliver-prd/');
  assert.equal(prd.source, 'skills/deliver-prd/SKILL.md');
});

import { renderIndex } from './gen-resource-index.mjs';

test('renderIndex emits banner, sections, and correct link columns', () => {
  const model = {
    routes: new Set(),
    docs: [{ label: 'Guides', rows: [{ name: 'Prompt Gallery', description: 'Real | prompts', route: '/guides/prompt-gallery/', source: 'site/src/content/docs/guides/prompt-gallery.md' }] }],
    skills: [{ group: 'deliver', label: 'Deliver', rows: [{ name: 'deliver-prd', description: 'PRD skill', route: '/skills/deliver/deliver-prd/', source: 'skills/deliver-prd/SKILL.md' }] }],
    workflows: [{ name: 'feature-kickoff', description: 'Kickoff', route: '/workflows/feature-kickoff/', source: '_workflows/feature-kickoff.md' }],
    samples: [{ skill: 'deliver-prd', sourceDir: 'library/skill-output-samples/deliver-prd/', rows: [{ scenario: 'storevine / campaigns', route: '/samples/deliver-prd/sample_deliver-prd_storevine_campaigns/', source: 'library/skill-output-samples/deliver-prd/sample_deliver-prd_storevine_campaigns.md' }] }],
    showcase: [{ thread: 'storevine', route: '/showcase/storevine/' }],
  };
  const md = renderIndex(model);
  assert.match(md, /^# PM Skills - Resource Index/);
  assert.match(md, /<!-- GENERATED by scripts\/gen-resource-index\.mjs/);
  assert.match(md, /\[page\]\(https:\/\/product-on-purpose\.github\.io\/pm-skills\/guides\/prompt-gallery\/\)/);
  assert.match(md, /\[SKILL\.md\]\(\.\.\/skills\/deliver-prd\/SKILL\.md\)/);
  assert.match(md, /\.\.\/library\/skill-output-samples\/deliver-prd\/sample_deliver-prd_storevine_campaigns\.md/);
  assert.match(md, /## Workflows/);
  assert.match(md, /## Showcase/);
  assert.match(md, /Real \\\| prompts/);
  assert.ok(md.endsWith('\n'));
  const EMDASH = String.fromCharCode(0x2014);
  assert.equal(md.includes(EMDASH), false, 'renderer emits no em-dashes');
});

import { normalizeEol } from './gen-resource-index.mjs';

test('normalizeEol converts CRLF to LF', () => {
  assert.equal(normalizeEol('a\r\nb\r\n'), 'a\nb\n');
});
