#!/usr/bin/env bash
# validate-docs-frontmatter.sh - Validate frontmatter on rendered docs pages.
#
# Every docs/**/*.md (excluding docs/internal/ and mkdocs.yml exclude_docs)
# should have well-formed YAML frontmatter with required fields title and
# description. Optional fields (tags, date) validated when present.
#
# Posture: ADVISORY in v2.13.0 (deviation from audit's "enforcing" posture).
# Many pre-existing rendered docs lack frontmatter; cleanup is a Bucket B
# or v2.14 effort. Shipping enforcing now would block CI on existing drift.
# Promote to enforcing once frontmatter coverage is complete.
#
# Exit codes:
#   0 - All checked docs pass OR advisory mode (default)
#   1 - Findings AND --strict was passed
#
# Usage:
#   ./scripts/validate-docs-frontmatter.sh
#   ./scripts/validate-docs-frontmatter.sh --strict

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MKDOCS_YML="$ROOT/mkdocs.yml"

STRICT=false
if [[ "${1:-}" == "--strict" ]]; then
  STRICT=true
fi

echo "=== Docs Frontmatter Validation ==="
echo ""

# Extract exclude_docs entries from mkdocs.yml
EXCLUDE_PATHS=$(awk '
  /^exclude_docs:/ { in_exc=1; next }
  in_exc && /^[^[:space:]#]/ { in_exc=0; next }
  in_exc {
    line=$0
    sub(/^[[:space:]]+/, "", line)
    if (length(line) > 0) print line
  }
' "$MKDOCS_YML" 2>/dev/null || true)

# Auto-skip patterns: rendered docs that legitimately may not need frontmatter
AUTO_SKIP_PATTERNS=(
  "templates/*"
  "skills/*"        # auto-generated; description from SKILL.md frontmatter has different length rules
  "workflows/*"     # auto-generated from _workflows/
  "showcase/*"      # auto-generated
  "reference/commands.md"  # auto-generated by generate-skill-pages.py
  "releases/Release_v*.md" # release notes; transitively reachable from releases/index.md
)

is_excluded() {
  local fs_file="$1"
  while IFS= read -r exc_path; do
    [[ -z "$exc_path" ]] && continue
    local exc_clean="${exc_path#/}"
    if [[ "$exc_clean" == */ ]]; then
      [[ "$fs_file" == "$exc_clean"* ]] && return 0
    else
      [[ "$fs_file" == "$exc_clean" ]] && return 0
    fi
  done <<< "$EXCLUDE_PATHS"

  for pattern in "${AUTO_SKIP_PATTERNS[@]}"; do
    [[ "$fs_file" == $pattern ]] && return 0
  done
  return 1
}

# Collect docs files to validate
FS_FILES=$(find "$ROOT/docs" -name "*.md" -type f \
  | grep -v "/docs/internal/" \
  | sed "s|$ROOT/docs/||" \
  | sort)

FAIL_COUNT=0
WARN_COUNT=0
CHECKED=0
declare -a FINDINGS

while IFS= read -r fs_file; do
  [[ -z "$fs_file" ]] && continue
  if is_excluded "$fs_file"; then continue; fi

  full_path="$ROOT/docs/$fs_file"
  CHECKED=$((CHECKED + 1))

  # Read first line and detect frontmatter delimiter
  first_line=$(head -1 "$full_path" 2>/dev/null || echo "")

  if [[ "$first_line" != "---" ]]; then
    FINDINGS+=("docs/$fs_file: missing frontmatter delimiter (first line is not '---')")
    WARN_COUNT=$((WARN_COUNT + 1))
    continue
  fi

  # Find closing delimiter
  end_line=$(awk 'NR>1 && /^---$/ { print NR; exit }' "$full_path")
  if [[ -z "$end_line" ]]; then
    FINDINGS+=("docs/$fs_file: frontmatter has opening '---' but no closing '---'")
    FAIL_COUNT=$((FAIL_COUNT + 1))
    continue
  fi

  # Extract frontmatter block
  frontmatter=$(sed -n "2,$((end_line - 1))p" "$full_path")

  # Check required: title
  title=$(echo "$frontmatter" | grep -m1 '^title:' | sed -E 's/^title:[[:space:]]*//' | sed 's/^"//;s/"$//;s/^'\''//;s/'\''$//')
  if [[ -z "$title" ]]; then
    FINDINGS+=("docs/$fs_file: missing required field 'title'")
    FAIL_COUNT=$((FAIL_COUNT + 1))
  elif [[ ${#title} -gt 80 ]]; then
    FINDINGS+=("docs/$fs_file: title exceeds 80 chars (${#title})")
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi

  # Check required: description
  description=$(echo "$frontmatter" | grep -m1 '^description:' | sed -E 's/^description:[[:space:]]*//' | sed 's/^"//;s/"$//;s/^'\''//;s/'\''$//')
  if [[ -z "$description" ]]; then
    # description might span multiple lines (>- or |); try block scalar
    desc_block=$(awk '
      /^description:[[:space:]]*[>|]/ { in_desc=1; next }
      in_desc && /^[a-z]/ { in_desc=0 }
      in_desc { gsub(/^[[:space:]]+/, ""); print }
    ' <<< "$frontmatter")
    description="$desc_block"
  fi

  if [[ -z "$description" ]]; then
    FINDINGS+=("docs/$fs_file: missing required field 'description'")
    FAIL_COUNT=$((FAIL_COUNT + 1))
  else
    desc_len=${#description}
    if [[ $desc_len -lt 50 ]]; then
      FINDINGS+=("docs/$fs_file: description shorter than 50 chars ($desc_len)")
      WARN_COUNT=$((WARN_COUNT + 1))
    elif [[ $desc_len -gt 300 ]]; then
      FINDINGS+=("docs/$fs_file: description exceeds 300 chars ($desc_len)")
      WARN_COUNT=$((WARN_COUNT + 1))
    fi
  fi

done <<< "$FS_FILES"

echo "Files checked: $CHECKED"
echo "Excluded by mkdocs.yml exclude_docs or auto-skip: $(($(echo "$FS_FILES" | grep -c .) - CHECKED))"
echo ""

TOTAL=$((FAIL_COUNT + WARN_COUNT))

if [[ $TOTAL -eq 0 ]]; then
  echo "PASS: All $CHECKED docs have valid frontmatter."
  exit 0
fi

echo "Frontmatter findings: $FAIL_COUNT failures, $WARN_COUNT warnings"
echo ""
for f in "${FINDINGS[@]:0:50}"; do
  echo "  $f"
done

if [[ ${#FINDINGS[@]} -gt 50 ]]; then
  echo ""
  echo "  ... and $((${#FINDINGS[@]} - 50)) more"
fi
echo ""

if [[ "$STRICT" == "true" ]]; then
  echo "FAIL (--strict): $TOTAL frontmatter finding(s)."
  exit 1
else
  echo "WARN: $TOTAL frontmatter finding(s) (advisory mode)."
  echo "  Many rendered docs currently lack frontmatter; cleanup is a Bucket B / v2.14 effort."
  echo "  Promote to enforcing (--strict in CI) once frontmatter coverage is complete."
  exit 0
fi
